#!/bin/bash
# Weekly Quality Check Reminder for ANISA

echo "🔔 ANISA Weekly Quality Check Reminder"
echo "====================================="
echo ""
echo "📅 It's time for your weekly code quality review!"
echo ""
echo "🚀 Quick Commands:"
echo "  • Basic report: python3 code-quality/weekly-report.py"
echo "  • Full analysis: ./code-quality/scripts/weekly-quality-check.sh"
echo "  • Save report: python3 code-quality/weekly-report.py --save"
echo ""
echo "📊 Review these areas:"
echo "  • Test coverage (target: 80%+)"
echo "  • Code complexity (target: ≤5)"
echo "  • Linting issues (target: 0)"
echo "  • Security vulnerabilities (target: 0)"
echo "  • Documentation coverage (target: 80%+)"
echo "  • Code size management (target: ≤100 lines/file)"
echo ""
echo "💡 Remember: Quality is everyone's responsibility!"
echo "   Address critical issues first, then work on improvements."
echo ""
echo "📈 Track your progress and celebrate improvements!"
